name: Let's Encrypt for DOBS
description: |
  Trusted SSL certificates at zero cost
version: 0.5.1
category: Security
maintainer: Jan Bruder <jan@rancher.com>
license: The MIT License
projectURL: http://www.github.com/janeczku/rancher-letsencrypt
